# Generated by Django 5.0.6 on 2024-11-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='short_discription',
        ),
        migrations.AddField(
            model_name='offer',
            name='short_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
