# Generated by Django 5.0.6 on 2024-08-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Restaurant')),
                ('title', models.CharField(max_length=225)),
                ('short_discription', models.CharField(max_length=225)),
                ('rating', models.FloatField()),
                ('timer', models.IntegerField()),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'db_table': 'restaurant_restaurant',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_category')),
                ('title', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Restaurant_Category',
                'verbose_name_plural': 'Restaurant_Categories',
                'db_table': 'restaurant_Restaurant_Category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'foodcategory',
                'verbose_name_plural': 'foodcategories',
                'db_table': 'foodcategory',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Food')),
                ('name', models.CharField(max_length=225)),
                ('price', models.FloatField()),
                ('is_veg', models.BooleanField(default=False)),
                ('foodcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.foodcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'db_table': 'food',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantcategory'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Restaurant_Category')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'slideries',
                'db_table': 'restaurant_slider',
                'ordering': ['-id'],
            },
        ),
    ]
